### PR TITLE
Fix CI failures

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

### CODE REVIEW

**Comment by gaocegege** [comment]
It seems that we have no item in GCS

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_hp-tuning/27/kubeflow-hp-tuning-presubmit

**Comment by gaocegege** [comment]
@jlewi 

I meet with one problem when I am trying to fix CI failures. I'd appreciate it if you could have a look.

https://console.cloud.google.com/kubernetes/pod/us-east1-d/kubeflow-testing/kubeflow-test-infra/kubeflow-hp-tuning-presubmit-e2e-27-4e8c7ed-19-af0f-2710394068?project=kubeflow-ci&tab=logs&duration=PT1H&container_summary_list_tablesize=10&log_entry_list_tablesize=50

I think it may be caused by some features I don't know in GKE. I tried to hack it https://github.com/kubeflow/hp-tuning/pull/27/commits/aacd31e0bd0b97282c7e924aea9278fc30bcd5ec but failed.

**Comment by gaocegege** [comment]
/assign @YujiOshima 

Thanks to jose5918@ , we solved the issue in GKE and CI should work now.

**Comment by YujiOshima** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉
Thank you @gaocegege @jose5918 !!!
/lgtm

**Pull request merged**
